### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by oehm-smith** [geoHeil/ionic2WebpackTypescriptNonNativeModule#1]
Hi geoHeil,

I followed your conversation at https://github.com/highsource/jsonix/issues/139 as I'm looking for typings for Jsonix.

I tried your project and it doesn't run.  Initially there was a dependencies problem.  I locked all dependencies in the `packages.json` to bug fixes by changing `^` to `~`.  Still problems.  I removed `~` so the versions you initially specifed are brought in.  No dependencies problems but it doesn't `ionic start`.  It errors with:

```
TypeScript error: .../ionic2WebpackTypescriptNonNativeModule/app/pages/home-page/home-page.ts(4,22): Error TS2307: Cannot find module '../../node_modules/jsonix/jsonix'.
Error: Cannot find module '../../node_modules/jsonix/jsonix' from '.../ionic2WebpackTypescriptNonNativeModule/app/pages/home-page'
```

I have the latest ionic - perhaps how this works has changed (I've not worked with it before)

Any ideas?

**Comment by geoHeil** [comment]
Hi
This should be not a problem related to ionic but rather regarding module
loading and typings.

I have to admit I did not solve the problem and was lucky to get a nice
rest api in the end wich is not XML based.
Brooke Smith notifications@github.com schrieb am Do., 8. Sep. 2016 um
07:37:

**Comment by oehm-smith** [comment]
Ok thanks. I'm pursuing a pure javascript solution and may return to TS jsonix later.
